export const LOADING_USER = 'LOADING_USER';
export const TRACK_LOAN_APPLICATION = 'TRACK_LOAN_APPLICATION';
export const LOGIN = 'LOGIN';
export const GET_USER_WALLET = 'GET_USER_WALLET';
export const GET_TOTAL_WALLET = 'GET_TOTAL_WALLET';
export const FIND_ALL_USERS = 'FIND_ALL_USERS';
export const FIND_ALL_REQUESTS = 'FIND_ALL_REQUESTS';
